root: true

extends:
    "eslint:recommended"

env:
    node: true
    es6: true

parserOptions:
    ecmaVersion: 2017

rules:
    indent:
        - error
        - tab
        - SwitchCase: 1
    semi:
        - error
        - always
    curly:
        - error
    complexity:
        - error
        - 10
    eqeqeq:
        - error
        - always